version: "3"
services:
  mosquitto:
    image: toke/mosquitto
    ports: 
      - 1883:1883
  pi_c:
    depends_on:
      - mosquitto
    build:
      context: ./pi_c
      dockerfile: Dockerfile
  laptop_2:
    depends_on:
      - mosquitto
    build:
      context: ./laptop_2
      dockerfile: Dockerfile